# Generated by Django 5.1.7 on 2025-03-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='vk_avatar_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vk_discussion_url',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('AEG', 'Ремонт'), ('GBB', 'Газовые приводы'), ('UPG', 'Апгрейды')], max_length=3, verbose_name='Тип услуги'),
        ),
    ]
