# Generated by Django 5.1.7 on 2025-03-24 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_review_options_review_author_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vk_post_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, message='Описание должно содержать минимум 100 символов'), django.core.validators.MaxLengthValidator(300, message='Описание должно содержать максимум 300 символов')], verbose_name='Описание'),
        ),
    ]
