# Generated by Django 5.1.7 on 2025-04-04 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_review_author_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(250, message='Описание должно содержать минимум 250 символов'), django.core.validators.MaxLengthValidator(300, message='Описание должно содержать максимум 300 символов')], verbose_name='Описание'),
        ),
    ]
